import type { Metadata } from "next";
import { racing, robotC } from "@/app/_ui/fonts";
import "./globals.css";
import { Header } from "./_ui/components/Header";
import { StoreProvider } from "./_store/useShopStore";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotC.variable} ${racing.variable} `}>
        <StoreProvider>
          <Header />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
